"""Initial tables

Revision ID: 001_initial_tables
Revises: 
Create Date: 2026-02-28 11:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '001_initial_tables'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建stocks表
    op.create_table('stocks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(length=20), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('market', sa.String(length=10), nullable=False),
        sa.Column('industry', sa.String(length=100), nullable=True),
        sa.Column('sector', sa.String(length=100), nullable=True),
        sa.Column('listing_date', sa.Date(), nullable=True),
        sa.Column('total_shares', sa.BigInteger(), nullable=True),
        sa.Column('circulating_shares', sa.BigInteger(), nullable=True),
        sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column('circulating_market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    
    # 创建stock_daily表
    op.create_table('stock_daily',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('stock_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('open_price', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('high_price', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('low_price', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('close_price', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('adj_close', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('volume', sa.BigInteger(), nullable=True),
        sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column('change', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('change_percent', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('turnover_rate', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('pe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('pb_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('stock_id', 'date', name='idx_stock_date')
    )
    op.create_index(op.f('ix_stock_daily_date'), 'stock_daily', ['date'], unique=False)
    op.create_index(op.f('ix_stock_daily_id'), 'stock_daily', ['id'], unique=False)
    op.create_index(op.f('ix_stock_daily_stock_id'), 'stock_daily', ['stock_id'], unique=False)
    
    # 创建technical_indicators表
    op.create_table('technical_indicators',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('stock_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('ma5', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('ma10', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('ma20', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('ma30', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('ma60', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('ma120', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('ma250', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('boll_upper', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('boll_middle', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('boll_lower', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('macd', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('macd_signal', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('macd_histogram', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('rsi6', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('rsi12', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('rsi24', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('k_value', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('d_value', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('j_value', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('volume_ma5', sa.BigInteger(), nullable=True),
        sa.Column('volume_ma10', sa.BigInteger(), nullable=True),
        sa.Column('obv', sa.BigInteger(), nullable=True),
        sa.Column('trend_score', sa.Integer(), nullable=True),
        sa.Column('volatility', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('stock_id', 'date', name='idx_tech_stock_date')
    )
    op.create_index(op.f('ix_technical_indicators_date'), 'technical_indicators', ['date'], unique=False)
    op.create_index(op.f('ix_technical_indicators_id'), 'technical_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_technical_indicators_stock_id'), 'technical_indicators', ['stock_id'], unique=False)
    
    # 创建ml_predictions表
    op.create_table('ml_predictions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('stock_id', sa.Integer(), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=False),
        sa.Column('prediction_date', sa.Date(), nullable=False),
        sa.Column('target_date', sa.Date(), nullable=False),
        sa.Column('predicted_price', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('predicted_change', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('features', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('actual_price', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('actual_change', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('prediction_error', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('is_correct', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_id'), 'ml_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_prediction_date'), 'ml_predictions', ['prediction_date'], unique=False)
    op.create_index(op.f('ix_ml_predictions_stock_id'), 'ml_predictions', ['stock_id'], unique=False)
    op.create_index('idx_pred_stock_model_date', 'ml_predictions', ['stock_id', 'model_name', 'prediction_date'], unique=False)
    
    # 创建users表
    op.create_table('users',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=100), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_superuser', sa.Boolean(), nullable=True),
        sa.Column('notification_enabled', sa.Boolean(), nullable=True),
        sa.Column('risk_tolerance', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # 创建user_portfolios表
    op.create_table('user_portfolios',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('stock_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('avg_cost', sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column('current_price', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('market_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('profit_loss', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('profit_loss_percent', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('first_buy_date', sa.Date(), nullable=True),
        sa.Column('last_buy_date', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'stock_id', name='idx_portfolio_user_stock')
    )
    op.create_index(op.f('ix_user_portfolios_id'), 'user_portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_user_portfolios_stock_id'), 'user_portfolios', ['stock_id'], unique=False)
    op.create_index(op.f('ix_user_portfolios_user_id'), 'user_portfolios', ['user_id'], unique=False)
    
    # 创建data_sources表
    op.create_table('data_sources',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('source_type', sa.String(length=50), nullable=False),
        sa.Column('base_url', sa.String(length=500), nullable=True),
        sa.Column('api_key', sa.String(length=255), nullable=True),
        sa.Column('rate_limit', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('last_sync', sa.DateTime(), nullable=True),
        sa.Column('sync_status', sa.String(length=20), nullable=True),
        sa.Column('success_rate', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('avg_response_time', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    
    # 创建data_sync_logs表
    op.create_table('data_sync_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_id', sa.Integer(), nullable=False),
        sa.Column('sync_type', sa.String(length=50), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('records_fetched', sa.Integer(), nullable=True),
        sa.Column('records_processed', sa.Integer(), nullable=True),
        sa.Column('records_failed', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sync_logs_id'), 'data_sync_logs', ['id'], unique=False)
    op.create_index(op.f('ix_data_sync_logs_source_id'), 'data_sync_logs', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_sync_logs_source_id'), table_name='data_sync_logs')
    op.drop_index(op.f('ix_data_sync_logs_id'), table_name='data_sync_logs')
    op.drop_table('data_sync_logs')
    
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    
    op.drop_index(op.f('ix_user_portfolios_user_id'), table_name='user_portfolios')
    op.drop_index(op.f('ix_user_portfolios_stock_id'), table_name='user_portfolios')
    op.drop_index(op.f('ix_user_portfolios_id'), table_name='user_portfolios')
    op.drop_table('user_portfolios')
    
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    
    op.drop_index('idx_pred_stock_model_date', table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_stock_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_prediction_date'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    
    op.drop_index(op.f('ix_technical_indicators_stock_id'), table_name='technical_indicators')
    op.drop_index(op.f('ix_technical_indicators_id'), table_name='technical_indicators')
    op.drop_index(op.f('ix_technical_indicators_date'), table_name='technical_indicators')
    op.drop_table('technical_indicators')
    
    op.drop_index(op.f('ix_stock_daily_stock_id'), table_name='stock_daily')
    op.drop_index(op.f('ix_stock_daily_id'), table_name='stock_daily')
    op.drop_index(op.f('ix_stock_daily_date'), table_name='stock_daily')
    op.drop_table('stock_daily')
    
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###